In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.15.0


In [2]:
# Excercise 3 - Create two tensors containing random values between 0 and 1 with shape [5, 300]
ten1 = tf.random.uniform(shape=[5,300], minval=0, maxval=1, dtype=tf.float16)
ten2 = tf.random.uniform(shape=[5,300], minval=0, maxval=1, dtype=tf.float16)
ten1, ten2

(<tf.Tensor: shape=(5, 300), dtype=float16, numpy=
 array([[0.335  , 0.3916 , 0.05273, ..., 0.8037 , 0.825  , 0.2334 ],
        [0.922  , 0.03516, 0.1797 , ..., 0.0781 , 0.0635 , 0.0703 ],
        [0.706  , 0.3857 , 0.083  , ..., 0.6143 , 0.2266 , 0.2334 ],
        [0.76   , 0.7256 , 0.3408 , ..., 0.2705 , 0.1465 , 0.2725 ],
        [0.07227, 0.6016 , 0.1074 , ..., 0.4434 , 0.21   , 0.03906]],
       dtype=float16)>,
 <tf.Tensor: shape=(5, 300), dtype=float16, numpy=
 array([[0.657  , 0.551  , 0.7617 , ..., 0.3184 , 0.5156 , 0.498  ],
        [0.09766, 0.2715 , 0.8584 , ..., 0.2715 , 0.4844 , 0.7744 ],
        [0.294  , 0.709  , 0.1885 , ..., 0.58   , 0.413  , 0.618  ],
        [0.2012 , 0.789  , 0.83   , ..., 0.1523 , 0.9727 , 0.11035],
        [0.4043 , 0.08105, 0.953  , ..., 0.5234 , 0.1328 , 0.5186 ]],
       dtype=float16)>)

In [3]:
# Excercise 4 - Multiply the two tensors you created in 3 using matrix multiplication.
tf.matmul(ten1,tf.transpose(ten2))

<tf.Tensor: shape=(5, 5), dtype=float16, numpy=
array([[76.44, 77.9 , 74.4 , 76.2 , 81.7 ],
       [73.94, 75.9 , 70.5 , 74.3 , 79.5 ],
       [76.25, 75.9 , 73.2 , 75.1 , 82.1 ],
       [77.5 , 78.6 , 75.25, 80.56, 83.  ],
       [73.56, 72.1 , 68.44, 74.8 , 74.1 ]], dtype=float16)>

In [4]:
# Excercise 5 - Multiply the two tensors you created in 3 using dot product.
tf.tensordot(ten1, tf.transpose(ten2), axes = 1)

<tf.Tensor: shape=(5, 5), dtype=float16, numpy=
array([[76.44, 77.9 , 74.4 , 76.2 , 81.7 ],
       [73.94, 75.9 , 70.5 , 74.3 , 79.5 ],
       [76.25, 75.9 , 73.2 , 75.1 , 82.1 ],
       [77.5 , 78.6 , 75.25, 80.56, 83.  ],
       [73.56, 72.1 , 68.44, 74.8 , 74.1 ]], dtype=float16)>

In [5]:
# Excercise 6 - Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
ten3 = tf.random.uniform(shape = [224, 224, 3], minval = 0, maxval = 1, dtype=tf.float16)
ten3

<tf.Tensor: shape=(224, 224, 3), dtype=float16, numpy=
array([[[0.1484 , 0.7773 , 0.716  ],
        [0.708  , 0.8555 , 0.07227],
        [0.5186 , 0.2588 , 0.0967 ],
        ...,
        [0.1807 , 0.59   , 0.9062 ],
        [0.0762 , 0.4375 , 0.8984 ],
        [0.04785, 0.658  , 0.5605 ]],

       [[0.5303 , 0.871  , 0.07227],
        [0.7324 , 0.374  , 0.3994 ],
        [0.0957 , 0.01172, 0.2051 ],
        ...,
        [0.4336 , 0.839  , 0.4902 ],
        [0.2266 , 0.1797 , 0.1533 ],
        [0.3564 , 0.9385 , 0.5156 ]],

       [[0.421  , 0.715  , 0.454  ],
        [0.658  , 0.672  , 0.9297 ],
        [0.543  , 0.782  , 0.5547 ],
        ...,
        [0.7    , 0.01758, 0.1787 ],
        [0.3096 , 0.209  , 0.8623 ],
        [0.8076 , 0.783  , 0.8203 ]],

       ...,

       [[0.09375, 0.707  , 0.3262 ],
        [0.1797 , 0.6064 , 0.8525 ],
        [0.3242 , 0.8213 , 0.1826 ],
        ...,
        [0.746  , 0.01172, 0.3857 ],
        [0.377  , 0.2432 , 0.084  ],
        [0.3604 , 0.249

In [6]:
# Excercise 7 - Find the min and max values of the tensor you created in 6 along the first axis.
tf.reduce_min(ten3[0])

<tf.Tensor: shape=(), dtype=float16, numpy=0.0>

In [10]:
# Excercise 8 - Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
ten4 = tf.random.uniform(shape = [1,224,224,3], minval = 0, maxval = 1)
ten4 = tf.squeeze(ten4)
ten4

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[4.3835616e-01, 4.0948761e-01, 2.4513066e-01],
        [9.9103975e-01, 4.7530711e-01, 6.0324740e-01],
        [7.6419771e-01, 8.7878799e-01, 1.3177073e-01],
        ...,
        [4.1735291e-02, 8.0937958e-01, 2.7666819e-01],
        [6.1631584e-01, 5.8642149e-01, 6.9790125e-02],
        [2.4134552e-01, 8.4474552e-01, 7.2156763e-01]],

       [[2.4950731e-01, 2.5064993e-01, 3.9622843e-01],
        [1.8945813e-01, 6.6441631e-01, 7.1177483e-03],
        [8.3545530e-01, 1.8425727e-01, 4.7628701e-01],
        ...,
        [4.3089986e-01, 1.8350613e-01, 4.9358547e-01],
        [4.9243557e-01, 5.8199823e-01, 6.4488888e-02],
        [9.3474710e-01, 7.8193319e-01, 4.7936487e-01]],

       [[3.7930739e-01, 9.7065330e-01, 8.7765479e-01],
        [9.0775251e-02, 6.6935980e-01, 4.8578775e-01],
        [1.5689433e-01, 4.4758916e-01, 6.4835572e-01],
        ...,
        [7.3679566e-01, 5.1067400e-01, 2.3138070e-01],
        [7.6435447e-01

In [11]:
# Excercise 9 - Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
ten5 = tf.constant(tf.range(0,10))
ten5 = tf.random.shuffle(ten5)
ten5

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([4, 8, 9, 6, 7, 2, 0, 3, 5, 1], dtype=int32)>

In [12]:
# Excercise 10 - One-hot encode the tensor you created in 9.
tf.one_hot(ten5, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>